### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [bobrowskibiz/kod8.5#2]
- [x] dobra rada jest taka, zeby uzywac operatora scislego porownania `===` zamiast `==` Mozesz poczytac o roznicy w necie. Aktualnie jak wpisze do jednej zmiennej `0`, a do drugiej nie wpisze nic, to wynik bedzie rowny zero, a to nieprawda
- [x] dorzuc tez jeden warunek, ktory wyswietli 'wynik nieokreslony', kiedy wpisze bledne dane np litery

**Comment by bobrowskibiz** [comment]
a) zmienione ale nadal nie widzę wpływu w tym przypadku gdyż
jeżeli wpisze w A 0 a w B nic to wynik i tak wyjdzie 0 albo moja matematyka mnie zawodzi:
0*0= 0 + 2*0*nic = 0 - nic = 0 ? czyż inaczej :>
b) dodane

**Comment by zdolny** [comment]
Zdaje sie, ze niepotrzebnie skomplikowalem problem. Generalnie rzutowanie typow jest w js troche zawile i zbyt duzo dygresji sie tutaj pojawia.
Chodzilo mi o to, ze to _nic_, o ktorym piszesz teoretycznie moze miec rozne wartosci, a pusty string nie jest rowny liczbie zero. Aczkolwiek praktycznie prompt i tak zwraca string, a w dzialaniu jest rzutowany na liczbe, wiec faktycznie wyjdzie tak, jak mowisz, ze pusty string zostanie zrzutowany na zero. Wiec przyjmijmy, ze pusty string podany przez usera traktujemy jako zero.

Czyli darujmy sobie te `isNaN` i zrob prosze po prostu 4 ify/elsy:
- `=== 0`
- `> 0`
- `< 0`
- reszta (nieprawidlowe dane)

**Comment by zdolny** [comment]
poprawilem wciecia i jest git
